version: '3'
services:
  web:
    build: .
    command: bash -c "bin/rails assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/quiz_drug_ingredients
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"